name: Show Secret

on: 
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Show secret value
        run: echo "Secret value: ${{ secrets.SECRET_KEY }}"
        run: echo "Host Password: ${{ secrets.EMAIL_HOST_PASSWORD }}"